### ISSUE TITLE
Problem in hosting

### ISSUE THREAD

**Issue by ph4t0o0o0om** [jmrashed/zkteco#1]
It works locally but when upload to hosting it's not working I think its a network problem? Do you have solution on how to fix this? Thanks

**Comment by jmrashed** [comment]
To resolve the issue, you need to ensure that both your web hosting and ZKTeco device are accessible under the same public IP address. If you're hosting your application in the cloud, you cannot use the local IP address of the ZKTeco device; instead, you must use its public IP address. Do you have access to the public IP address of your ZKTeco device?

**Comment by ph4t0o0o0om** [comment]
If im going to access my zkteco public address to do that I need to broadcast my local ip and bind it to a public IP . I need a firewall for that, So if thats the case in every location Im going to deploy a biotmetrics it always needs a firewall and a public ip to communicate with the system? Am I right?

**Comment by jmrashed** [comment]
Yes, you're correct. In order to access your ZKTeco device from a remote location, you typically need to configure port forwarding on your router/firewall to allow traffic from the internet to reach your device on your local network. This involves mapping a port on your public IP address to the internal IP address of your ZKTeco device.

Regarding the need for a firewall and a public IP address at each location where you deploy a biometrics system, it depends on your specific network setup and security requirements. In many cases, deploying a firewall is recommended for security reasons regardless of whether you're using biometrics or not. As for the public IP address, it's necessary if you want to access your device from the internet. However, there are other networking solutions that can be used to access devices on private networks without exposing them directly to the internet, such as VPNs or cloud-based solutions.

It's essential to consider the security implications and consult with a network specialist to ensure that your setup meets your security requirements while still allowing for remote access to your biometrics system.

**Comment by jmrashed** [comment]
I hope your issue has been resolved

**Comment by jmrashed** [comment]
I hope your issue has been resolved
